In [30]:
import os
import json
import pandas as pd
from collections import defaultdict

root = "/Users/shaury/Downloads/Indiana-CXR-Eden/outputs/metrics"

metrics = defaultdict(lambda : {})

rougeL = pd.read_csv(os.path.join(root, "rougeL.csv"))
bleu = pd.read_csv(os.path.join(root, "bleu.csv"))
radgraph = pd.read_csv(os.path.join(root, "radgraph_metric.csv"))
chexbert = pd.read_csv(os.path.join(root, "chexbert_scores.csv"))

In [31]:
rougeL

                                          Unnamed: 0         0
0  results_frontal_lateral_clahe_oversample_encod...  0.350200
1  results_frontal_lateral_no_clahe_no_oversample...  0.378218
2  results_frontal_no_clahe_no_oversample_encoder...  0.364758
3  results_frontal_lateral_no_clahe_oversample_en...  0.379976
4  results_frontal_no_clahe_no_oversample_encoder...  0.374361
5  results_frontal_lateral_clahe_no_oversample_en...  0.382542
6    results_frontal_clahe_no_oversample_encoder.csv  0.368795
7  results_frontal_lateral_no_clahe_no_oversample...  0.375921
8                       results_baseline_frontal.csv  0.195701
9               results_baseline_frontal_lateral.csv  0.197860

In [32]:
for _, row in rougeL.iterrows():
    metrics['rougeL'][row['Unnamed: 0']] = row['0']

for _, row in bleu.iterrows():
    metrics['bleu'][row['Unnamed: 0']] = row['0']

for _, row in radgraph.iterrows():
    metrics['radgraph'][row['Unnamed: 0']] = row['rg_e']

for _, row in chexbert.iterrows():
    metrics['chexbert_accuracy'][row['Unnamed: 0']] = row['chexbert_accuracy']
    d = eval(row['chexbert_class_report'])
    
    for key in d:
        metrics[f"{key}_f1"][row['Unnamed: 0']] = d[key]['f1-score']
        metrics[f"{key}_support"][row['Unnamed: 0']] = d[key]['support']

In [33]:
pd.DataFrame(metrics)

,rougeL,bleu,radgraph,chexbert_accuracy,Enlarged Cardiomediastinum_f1,Enlarged Cardiomediastinum_support,Cardiomegaly_f1,Cardiomegaly_support,Lung Opacity_f1,Lung Opacity_support,...,No Finding_f1,No Finding_support,micro avg_f1,micro avg_support,macro avg_f1,macro avg_support,weighted avg_f1,weighted avg_support,samples avg_f1,samples avg_support
results_frontal_lateral_clahe_oversample_encoder_decoder.csv,0.350200,9.31,0.274210,0.570707,0.066667,20.0,0.428571,18.0,0.421053,44.0,...,0.235294,25.0,0.233100,213.0,0.131881,213.0,0.231034,213.0,0.146284,213.0
results_frontal_lateral_no_clahe_no_oversample_encoder_decoder.csv,0.378218,10.52,0.321419,0.717172,0.181818,1.0,0.322581,7.0,0.290909,23.0,...,0.524390,87.0,0.348774,151.0,0.152938,151.0,0.401153,151.0,0.280303,151.0
results_frontal_no_clahe_no_oversample_encoder_decoder.csv,0.364758,9.58,0.300636,0.631313,0.000000,3.0,0.275862,5.0,0.185185,22.0,...,0.373134,57.0,0.206897,132.0,0.078563,132.0,0.216383,132.0,0.156662,132.0
results_frontal_lateral_no_clahe_oversample_encoder_decoder.csv,0.379976,13.70,0.310379,0.646465,0.000000,16.0,0.227273,20.0,0.289855,37.0,...,0.372881,41.0,0.254902,192.0,0.148901,192.0,0.251226,192.0,0.174122,192.0
results_frontal_no_clahe_no_oversample_encoder.csv,0.374361,9.41,0.295231,0.646465,0.000000,1.0,0.333333,6.0,0.295082,29.0,...,0.387597,52.0,0.258621,132.0,0.099768,132.0,0.279940,132.0,0.172150,132.0
results_frontal_lateral_clahe_no_oversample_encoder.csv,0.382542,10.58,0.304838,0.712121,0.000000,1.0,0.312500,8.0,0.310345,26.0,...,0.506494,77.0,0.334262,143.0,0.115243,143.0,0.393276,143.0,0.247571,143.0
results_frontal_clahe_no_oversample_encoder.csv,0.368795,9.83,0.298224,0.732323,0.000000,1.0,0.275862,5.0,0.208333,16.0,...,0.276423,46.0,0.198675,86.0,0.077139,86.0,0.236754,86.0,0.120539,86.0
results_frontal_lateral_no_clahe_no_oversample_encoder.csv,0.375921,9.61,0.310961,0.707071,0.000000,0.0,0.387097,7.0,0.310345,26.0,...,0.493506,77.0,0.344444,144.0,0.126752,144.0,0.400628,144.0,0.252597,144.0
results_baseline_frontal.csv,0.195701,0.80,0.157469,0.020202,0.000000,0.0,0.217195,197.0,0.280000,18.0,...,0.000000,0.0,0.123690,738.0,0.071855,738.0,0.133130,738.0,0.107548,738.0
results_baseline_frontal_lateral.csv,0.197860,0.84,0.158511,0.005051,0.000000,0.0,0.216216,198.0,0.250000,32.0,...,0.000000,0.0,0.123984,768.0,0.064568,768.0,0.135136,768.0,0.107167,768.0

In [36]:
bert_score_root = "/Users/shaury/Downloads/Indiana-CXR-Eden/outputs/metrics/bert_score"

ls = os.listdir(bert_score_root)

for name in ls:
    path = os.path.join(bert_score_root, name)
    df = pd.read_csv(path)
    bert_score_mean = df['bertscore_f1'].mean()
    metrics['bert_score'][name] = bert_score_mean

In [37]:
pd.DataFrame(metrics)

,rougeL,bleu,radgraph,chexbert_accuracy,Enlarged Cardiomediastinum_f1,Enlarged Cardiomediastinum_support,Cardiomegaly_f1,Cardiomegaly_support,Lung Opacity_f1,Lung Opacity_support,...,No Finding_support,micro avg_f1,micro avg_support,macro avg_f1,macro avg_support,weighted avg_f1,weighted avg_support,samples avg_f1,samples avg_support,bert_score
results_frontal_lateral_clahe_oversample_encoder_decoder.csv,0.350200,9.31,0.274210,0.570707,0.066667,20.0,0.428571,18.0,0.421053,44.0,...,25.0,0.233100,213.0,0.131881,213.0,0.231034,213.0,0.146284,213.0,0.937890
results_frontal_lateral_no_clahe_no_oversample_encoder_decoder.csv,0.378218,10.52,0.321419,0.717172,0.181818,1.0,0.322581,7.0,0.290909,23.0,...,87.0,0.348774,151.0,0.152938,151.0,0.401153,151.0,0.280303,151.0,0.942128
results_frontal_no_clahe_no_oversample_encoder_decoder.csv,0.364758,9.58,0.300636,0.631313,0.000000,3.0,0.275862,5.0,0.185185,22.0,...,57.0,0.206897,132.0,0.078563,132.0,0.216383,132.0,0.156662,132.0,0.941182
results_frontal_lateral_no_clahe_oversample_encoder_decoder.csv,0.379976,13.70,0.310379,0.646465,0.000000,16.0,0.227273,20.0,0.289855,37.0,...,41.0,0.254902,192.0,0.148901,192.0,0.251226,192.0,0.174122,192.0,0.941418
results_frontal_no_clahe_no_oversample_encoder.csv,0.374361,9.41,0.295231,0.646465,0.000000,1.0,0.333333,6.0,0.295082,29.0,...,52.0,0.258621,132.0,0.099768,132.0,0.279940,132.0,0.172150,132.0,0.941074
results_frontal_lateral_clahe_no_oversample_encoder.csv,0.382542,10.58,0.304838,0.712121,0.000000,1.0,0.312500,8.0,0.310345,26.0,...,77.0,0.334262,143.0,0.115243,143.0,0.393276,143.0,0.247571,143.0,0.941967
results_frontal_clahe_no_oversample_encoder.csv,0.368795,9.83,0.298224,0.732323,0.000000,1.0,0.275862,5.0,0.208333,16.0,...,46.0,0.198675,86.0,0.077139,86.0,0.236754,86.0,0.120539,86.0,0.941967
results_frontal_lateral_no_clahe_no_oversample_encoder.csv,0.375921,9.61,0.310961,0.707071,0.000000,0.0,0.387097,7.0,0.310345,26.0,...,77.0,0.344444,144.0,0.126752,144.0,0.400628,144.0,0.252597,144.0,0.941904
results_baseline_frontal.csv,0.195701,0.80,0.157469,0.020202,0.000000,0.0,0.217195,197.0,0.280000,18.0,...,0.0,0.123690,738.0,0.071855,738.0,0.133130,738.0,0.107548,738.0,0.900232
results_baseline_frontal_lateral.csv,0.197860,0.84,0.158511,0.005051,0.000000,0.0,0.216216,198.0,0.250000,32.0,...,0.0,0.123984,768.0,0.064568,768.0,0.135136,768.0,0.107167,768.0,0.900372

In [39]:
crimson_score_root = "/Users/shaury/Downloads/Indiana-CXR-Eden/outputs/metrics/crimson_out"

ls = os.listdir(crimson_score_root)

for name in ls:
    if name.endswith(".csv"):
        path = os.path.join(crimson_score_root, name)
        df = pd.read_csv(path)
        crimson_score = df['crimson_score'].mean()
        metrics['crimson_score'][name] = crimson_score

In [41]:
pd.DataFrame(metrics).to_csv("/Users/shaury/Downloads/Indiana-CXR-Eden/outputs/metrics/overall_metrics.csv")